### ISSUE TITLE
Does Hwacha supports RVV extension

### ISSUE THREAD

**Issue by siyy123** [ucb-bar/hwacha#25]
I'm wondering whether Hwacha supporrts the RISC-V Vector extension.

**Comment by colinschmidt** [comment]
No. It has its own custom RISC-V extension.
The hwacha architecture manual lives here: https://www2.eecs.berkeley.edu/Pubs/TechRpts/2015/EECS-2015-262.html

**Comment by hyz9181** [comment]
So is Hwacha supports the risc-v vector extension this year?
